### ISSUE TITLE
Unable to erase Application

### ISSUE THREAD

**Issue by mrdx-orb** [ORBNETSYS/InviTHINGS-Public#1]
When trying to delete an already added application 

<img width="620" alt="InviThings_delete-Error" src="https://user-images.githubusercontent.com/92920127/159246974-afdecc17-0cd4-45c1-a864-43ec04ee5f0a.PNG">

ERROR DETAILS
===================================

Cannot remove Item that has children (VideoOS.Platform)

------------------------------
Program location:

   at VideoOS.Platform.Proxy.ConfigApi.ConfigurationApiItemWrapper.ExecuteMethod(String methodId)
   at VideoOS.Platform.ConfigurationItems.MIPItemFolder.RemoveMIPItem(Item item)
   at VideoOS.Platform.Configuration.DeleteItemConfiguration(Guid platformDefinitionId, Item item)
   at InviThingsXProtect.Admin.InviThingsAppItemManager.DeleteItem(Item item)
   at VideoOS.Administration.AddIn.UserControlPlatformInfo.Delete(Item item)

===================================

Cannot remove Item that has children (mscorlib)

------------------------------
Program location:

Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at VideoOS.ConfigurationApi.ClientService.IConfigurationService.InvokeMethod(ConfigurationItem item, String method)
   at VideoOS.Platform.Proxy.ConfigApi.ConfigurationServiceClientDecorator.<>c__DisplayClass18_0.<InvokeMethod>b__0(ConfigurationServiceClient client)
   at VideoOS.Platform.Proxy.ConfigApi.ConfigurationServiceClientDecorator.CallWithRetry[TResult](Func`2 call)
   at VideoOS.Platform.Proxy.ConfigApi.ConfigurationApiItemWrapper.ExecuteMethod(String methodId)

**Comment by mrdx-orb** [comment]
Does erase if I remove the alarm points, then lines first. Still not ideal if this was a large system.
